{
    "name": "Internship Base",
    "version": "19.0.2.2.0",
    "category": "Custom",
    "summary": "Master data, configuration, shared mixins and security for the internship platform.",
    "author": "Internship CRM",
    "depends": ["base", "mail", "calendar"],
    "data": [
        "security/internship_security.xml",
        "security/ir.model.access.csv",
        "security/internship_record_rules.xml",
        "data/ir_sequence_data.xml",
        "data/internship_lookup_data.xml",
        "data/mail_templates.xml",
        "data/cron.xml",
        "wizards/reason_wizard_views.xml",
        "views/menus.xml",
        "views/lookup_views.xml",
        "views/university_views.xml",
        "views/program_views.xml",
        "views/student_views.xml",
        "views/company_views.xml",
        "views/opportunity_views.xml",
        "views/application_views.xml",
        "views/res_config_settings_views.xml",
        "views/res_users_views.xml",
    ],
    "demo": [
        "data/demo_data.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
