{
    "name": "Internship Reporting",
    "version": "19.0.2.1.0",
    "category": "Custom",
    "summary": "Live KPIs, dashboard and analyses for placements, monitoring, completion and Voice AI.",
    "author": "Internship CRM",
    "depends": [
        "internship_base",
        "internship_placement",
        "internship_agreement",
        "internship_monitoring",
        "internship_completion",
        "internship_crm",
        "internship_vapi",
    ],
    "data": [
        "security/internship_reporting_security.xml",
        "security/ir.model.access.csv",
        "data/report_data.xml",
        "views/internship_reporting_views.xml",
    ],
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
