{
    "name": "Internship Placement",
    "version": "19.0.1.0.0",
    "category": "Custom",
    "summary": "Central placement hub: stages, university review, document requests, leave, changes, termination.",
    "author": "Internship CRM",
    "depends": ["internship_base", "mail", "calendar", "portal"],
    "data": [
        "security/ir.model.access.csv",
        "security/internship_placement_rules.xml",
        "data/placement_stage_data.xml",
        "data/ir_sequence_data.xml",
        "data/mail_templates.xml",
        "data/cron.xml",
        "wizards/document_request_wizard_views.xml",
        "wizards/terminate_wizard_views.xml",
        "wizards/invite_company_wizard_views.xml",
        "views/placement_stage_views.xml",
        "views/placement_views.xml",
        "views/university_review_views.xml",
        "views/document_request_views.xml",
        "views/document_views.xml",
        "views/leave_views.xml",
        "views/change_request_views.xml",
        "views/master_data_views.xml",
        "views/menus.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
