from . import call_log
from . import vapi_event
from . import crm_lead
from . import student
from . import line_manager
from . import placement
from . import document_request
from . import attendance_monthly
from . import res_config_settings
