{
    "name": "Internship Completion",
    "version": "19.0.2.1.0",
    "category": "Custom",
    "summary": "Final report attempts, company evaluation, certificate, student feedback and completion checklist.",
    "author": "Internship CRM",
    "depends": ["internship_placement"],
    "data": [
        "security/internship_completion_security.xml",
        "security/ir.model.access.csv",
        "security/internship_completion_rules.xml",
        "data/ir_sequence_data.xml",
        "data/cron.xml",
        "report/completion_certificate.xml",
        "report/internship_certificate.xml",
        "views/internship_completion_views.xml",
        "views/completion_v2_views.xml",
    ],
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
