{
    "name": "Internship Monitoring",
    "version": "19.0.2.1.0",
    "category": "Custom",
    "summary": "Monthly attendance, performance, meetings and escalation for internships.",
    "author": "Internship CRM",
    "depends": ["internship_placement", "calendar"],
    "data": [
        "security/internship_monitoring_security.xml",
        "security/ir.model.access.csv",
        "security/internship_monitoring_rules.xml",
        "data/ir_sequence_data.xml",
        "data/mail_templates.xml",
        "data/cron.xml",
        "views/internship_monitoring_views.xml",
        "views/attendance_monthly_views.xml",
    ],
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
